default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: guilherme
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: RecipeApp

test:
  <<: *default
  database: RecipeApp_test

production:
  <<: *default
  database: RecipeApp_production
